config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'

  post '/users/edit', to: 'users#update'

  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end

  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

end

app/views/shared/_categories.html.erb
<nav class="navbar has-shadow" style="z-index: 5">
    <div class="container">
        <div class="navbar">
            <% @categories.each do |item| %>
              <%= link_to "#{item.name}", root_path, class: "navbar-item" %>
            <% end %>
        </div>
    </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <h1 class="title is-4">Maid2Work</h1>
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <div class="navbar-item">
                <div class="field has-addons">
                    <div class="control">
                        <input class="input" type="text" placeholder="Find services">
                    </div>
                    <div class="control">
                        <a class="button is-primary">Search</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <%= link_to 'Offer a new service', new_gig_path, class: "navbar-item" %>
            <a class="navbar-item">Browse Services</a>

            <% if (!user_signed_in?) %>
                <div class="navbar-item">
                    <div class="buttons">
                        <%= link_to  "Sign Up", new_user_registration_path, class: "button is-primary" %>
                        <%= link_to  "Login", new_user_session_path, class: "button is-light" %>
                    </div>
                </div>
            <% else %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        <figure class="image is-24x24 m-r-5">
                            <%= image_tag avatar_url(current_user), class: "is-rounded" %>
                        </figure>
                        <%= current_user.full_name %>
                    </a>

                    <div class="navbar-dropdown">
                        <%= link_to  "Personal details", edit_user_registration_path, class: "navbar-item" %>
                        <%= link_to 'Dashboard', dashboard_path, class: "navbar-item" %>
                        <hr class="navbar-divider">
                        <%= link_to  "Log out", destroy_user_session_path, method: :delete, class: "navbar-item" %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</nav>

<% if (user_signed_in?) && !current_page?(root_path) && !current_page?("/gigs/#{params[:id]}") && !current_page?("/users/#{params[:id]}") %>
    <nav class="navbar has-shadow" style="z-index: 5">
        <div class="container">
            <div class="navbar">
                <%= link_to 'Dashboard', dashboard_path, class: "navbar-item" %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Selling</a>
                    <div class="navbar-dropdown">
                        <%= link_to 'Create New Service', new_gig_path, class: "navbar-item" %>
                    </div>
                </div>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Buying</a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item">Post Request</a>
                        <a class="navbar-item">Manage Requests</a>
                    </div>
                </div>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Buyer Requests</a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item">Active Request</a>
                        <a class="navbar-item">Offers Sent</a>
                    </div>
                </div><div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Orders</a>
                    <div class="navbar-dropdown">
                        <%= link_to 'Selling Orders', selling_orders_path, class: "navbar-item" %>
                        <%= link_to 'Buying Orders', buying_orders_path, class: "navbar-item" %>
                    </div>
                </div>
                <%= link_to 'Earnings', dashboard_path, class: "navbar-item" %>
                <%= link_to 'Messages', dashboard_path, class: "navbar-item" %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Settings</a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item">Payment Method</a>
                        <a class="navbar-item">Payout Method</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
<% end %>

<script>
$(document).ready(function() {

  // Check for click events on the navbar burger icon
  $(".navbar-burger").click(function() {

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");

  });
});
</script>

app/views/shared/_notification.html.erb
<% unless flash.empty? %>
    <script>
        <% flash.each do |key, value| %>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          new Noty ({
              type: '<%= type %>',
              layout: 'topRight',
              timeout: '3000',
              theme: 'sunset',
              text: '<%= value %>'
          }).show();
        <% end %>
    </script>
<% end %>